import { motion } from "framer-motion";
import { RefreshCw, Copy, Download, FileText, Loader2 } from "lucide-react";
import { useState } from "react";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  LevelFormat,
  PageBreak,
} from "docx";

export interface CapstoneResult {
  title: string;
  description: string;
  features: string[];
  techStack: string[];
  methodology?: string;
}

interface ResultCardProps {
  result: CapstoneResult;
  onRegenerate: () => void;
  isLoading: boolean;
}

const downloadAsWord = async (result: CapstoneResult) => {
  const doc = new Document({
    numbering: {
      config: [
        {
          reference: "bullets",
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: "•",
              alignment: AlignmentType.LEFT,
              style: {
                paragraph: { indent: { left: 720, hanging: 360 } },
              },
            },
          ],
        },
      ],
    },
    styles: {
      default: { document: { run: { font: "Georgia", size: 24 } } },
      paragraphStyles: [
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 36, bold: true, font: "Georgia", color: "1a1a1a" },
          paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 0 },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 28, bold: true, font: "Georgia", color: "444444" },
          paragraph: { spacing: { before: 200, after: 100 }, outlineLevel: 1 },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 12240, height: 15840 },
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        children: [
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: result.title, bold: true })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
            children: [
              new TextRun({
                text: "Capstone Project Proposal",
                italics: true,
                color: "888888",
                size: 22,
              }),
            ],
          }),
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [new TextRun("Project Description")],
          }),
          new Paragraph({
            spacing: { after: 200 },
            children: [new TextRun(result.description)],
          }),
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [new TextRun("Key Features")],
          }),
          ...result.features.map(
            (f) =>
              new Paragraph({
                numbering: { reference: "bullets", level: 0 },
                children: [new TextRun(f)],
              })
          ),
          new Paragraph({ children: [] }),
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [new TextRun("Technology Stack")],
          }),
          ...result.techStack.map(
            (t) =>
              new Paragraph({
                numbering: { reference: "bullets", level: 0 },
                children: [new TextRun(t)],
              })
          ),
          new Paragraph({ children: [] }),
          ...(result.methodology
            ? [
                new Paragraph({
                  heading: HeadingLevel.HEADING_2,
                  children: [new TextRun("Methodology")],
                }),
                new Paragraph({
                  spacing: { after: 200 },
                  children: [new TextRun(result.methodology)],
                }),
              ]
            : []),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 600 },
            children: [
              new TextRun({
                text: "Generated by Thesify",
                italics: true,
                color: "aaaaaa",
                size: 18,
              }),
            ],
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${result.title.replace(/\s+/g, "-")}-proposal.docx`;
  a.click();
  URL.revokeObjectURL(url);
};

const generateAndDownloadResearchPaper = async (result: CapstoneResult) => {
  const apiBaseUrl = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:5147";

  const response = await fetch(`${apiBaseUrl}/api/capstone/research-paper`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      title: result.title,
      description: result.description,
      features: result.features,
      tech_Stack: result.techStack,
      methodology: result.methodology ?? "",
    }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error?.error ?? "Failed to generate research paper.");
  }

  const data = await response.json();
  const paperContent: string = data.content;

  const lines = paperContent.split("\n");
  const children: Paragraph[] = [];

  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { before: 1440, after: 240 },
      children: [new TextRun({ text: result.title, bold: true })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [new TextRun({ text: "Research Paper", italics: true, size: 26, color: "666666" })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 1440 },
      children: [
        new TextRun({
          text: `Technology Stack: ${result.techStack.join(", ")}`,
          size: 20,
          color: "888888",
        }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] })
  );

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      children.push(new Paragraph({ children: [] }));
    } else if (trimmed.startsWith("# ")) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun(trimmed.replace(/^# /, ""))],
        })
      );
    } else if (trimmed.startsWith("## ")) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun(trimmed.replace(/^## /, ""))],
        })
      );
    } else if (trimmed.startsWith("### ")) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun({ text: trimmed.replace(/^### /, ""), bold: true })],
        })
      );
    } else if (trimmed.startsWith("- ") || trimmed.startsWith("• ")) {
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun(trimmed.replace(/^[-•] /, ""))],
        })
      );
    } else {
      children.push(
        new Paragraph({
          spacing: { after: 120 },
          children: [new TextRun(trimmed)],
        })
      );
    }
  }

  const paperDoc = new Document({
    styles: {
      default: { document: { run: { font: "Georgia", size: 24 } } },
      paragraphStyles: [
        {
          id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
          run: { size: 36, bold: true, font: "Georgia", color: "1a1a1a" },
          paragraph: { spacing: { before: 360, after: 120 }, outlineLevel: 0 },
        },
        {
          id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
          run: { size: 28, bold: true, font: "Georgia", color: "444444" },
          paragraph: { spacing: { before: 240, after: 80 }, outlineLevel: 1 },
        },
        {
          id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
          run: { size: 24, bold: true, font: "Georgia", color: "555555" },
          paragraph: { spacing: { before: 180, after: 60 }, outlineLevel: 2 },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 12240, height: 15840 },
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1800 },
          },
        },
        children,
      },
    ],
  });

  const blob = await Packer.toBlob(paperDoc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${result.title.replace(/\s+/g, "-")}-research-paper.docx`;
  a.click();
  URL.revokeObjectURL(url);
};

const ResultCard = ({ result, onRegenerate, isLoading }: ResultCardProps) => {
  const [copied, setCopied] = useState(false);
  const [isDownloadingWord, setIsDownloadingWord] = useState(false);
  const [isGeneratingPaper, setIsGeneratingPaper] = useState(false);

  const handleCopy = () => {
    const text = `Title: ${result.title}\n\nDescription: ${result.description}\n\nFeatures:\n${result.features
      .map((f) => `- ${f}`)
      .join("\n")}\n\nTech Stack: ${result.techStack.join(", ")}${
      result.methodology ? `\n\nMethodology: ${result.methodology}` : ""
    }`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadWord = async () => {
    setIsDownloadingWord(true);
    try {
      await downloadAsWord(result);
    } catch (err) {
      console.error("Word download failed:", err);
      alert("Failed to generate Word file. Please try again.");
    } finally {
      setIsDownloadingWord(false);
    }
  };

  const handleGenerateResearchPaper = async () => {
    setIsGeneratingPaper(true);
    try {
      await generateAndDownloadResearchPaper(result);
    } catch (err: any) {
      console.error("Research paper failed:", err);
      alert(err.message ?? "Failed to generate research paper. Please try again.");
    } finally {
      setIsGeneratingPaper(false);
    }
  };

  return (
    // On mobile this is a normal block so the page scrolls naturally.
    // On desktop it sits inside an overflow-y-auto panel.
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="w-full pb-6 lg:pb-0"
    >
      <div className="rounded-lg sm:rounded-2xl border border-stone-200 dark:border-stone-700 bg-white dark:bg-stone-800 shadow-sm overflow-hidden">

        {/* Header */}
        <div className="px-4 sm:px-6 py-4 sm:py-5 border-b border-stone-100 dark:border-stone-700 bg-stone-50 dark:bg-stone-900">
          <p className="text-[10px] sm:text-xs font-semibold tracking-widest text-stone-400 dark:text-stone-500 uppercase mb-1.5">
            Generated Proposal
          </p>
          <h3
            className="text-lg sm:text-xl font-semibold text-stone-900 dark:text-white leading-snug"
            style={{ fontFamily: "'DM Serif Display', serif" }}
          >
            {result.title}
          </h3>
        </div>

        <div className="p-4 sm:p-6 space-y-4 sm:space-y-6">

          {/* Description */}
          <section>
            <h4 className="text-[10px] sm:text-[11px] font-semibold text-stone-400 dark:text-stone-500 uppercase tracking-widest mb-2">
              Description
            </h4>
            <p className="text-stone-700 dark:text-stone-300 text-xs sm:text-sm leading-relaxed font-light">
              {result.description}
            </p>
          </section>

          <div className="border-t border-stone-100 dark:border-stone-700" />

          {/* Features */}
          <section>
            <h4 className="text-[10px] sm:text-[11px] font-semibold text-stone-400 dark:text-stone-500 uppercase tracking-widest mb-3">
              Key Features
            </h4>
            <ul className="space-y-2">
              {result.features.map((feature, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -8 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.07 * i }}
                  className="flex items-start gap-2 sm:gap-2.5 text-stone-700 dark:text-stone-300 text-xs sm:text-sm"
                >
                  <span className="mt-1 sm:mt-1.5 h-1 sm:h-1.5 w-1 sm:w-1.5 rounded-full bg-stone-400 dark:bg-stone-500 shrink-0" />
                  <span className="font-light leading-relaxed">{feature}</span>
                </motion.li>
              ))}
            </ul>
          </section>

          <div className="border-t border-stone-100 dark:border-stone-700" />

          {/* Tech Stack */}
          <section>
            <h4 className="text-[10px] sm:text-[11px] font-semibold text-stone-400 dark:text-stone-500 uppercase tracking-widest mb-3">
              Tech Stack
            </h4>
            <div className="flex flex-wrap gap-1 sm:gap-1.5">
              {result.techStack.map((tech) => (
                <span
                  key={tech}
                  className="px-2 sm:px-2.5 py-0.5 sm:py-1 rounded-md bg-stone-100 dark:bg-stone-700 text-stone-600 dark:text-stone-200 text-[10px] sm:text-xs font-medium border border-stone-200 dark:border-stone-600"
                >
                  {tech}
                </span>
              ))}
            </div>
          </section>

          {/* Methodology */}
          {result.methodology && (
            <>
              <div className="border-t border-stone-100 dark:border-stone-700" />
              <section>
                <h4 className="text-[10px] sm:text-[11px] font-semibold text-stone-400 dark:text-stone-500 uppercase tracking-widest mb-2">
                  Methodology
                </h4>
                <p className="text-stone-700 dark:text-stone-300 text-xs sm:text-sm leading-relaxed font-light">
                  {result.methodology}
                </p>
              </section>
            </>
          )}
        </div>

        {/* Actions */}
        <div className="px-4 sm:px-6 py-3 sm:py-4 border-t border-stone-100 dark:border-stone-700 bg-stone-50 dark:bg-stone-900 flex flex-wrap gap-2">
          <button
            onClick={onRegenerate}
            disabled={isLoading}
            className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-stone-900 dark:bg-white text-white dark:text-black text-xs font-medium hover:bg-stone-800 dark:hover:bg-stone-200 transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`h-3.5 w-3.5 ${isLoading ? "animate-spin" : ""}`} />
            Regenerate
          </button>

          <button
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg border border-stone-200 dark:border-stone-600 bg-white dark:bg-stone-800 text-stone-600 dark:text-stone-300 text-xs font-medium hover:bg-stone-50 dark:hover:bg-stone-700 transition-colors"
          >
            <Copy className="h-3.5 w-3.5" />
            {copied ? "Copied" : "Copy"}
          </button>

          <button
            onClick={handleDownloadWord}
            disabled={isDownloadingWord}
            className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg border border-stone-200 dark:border-stone-600 bg-white dark:bg-stone-800 text-stone-600 dark:text-stone-300 text-xs font-medium hover:bg-stone-50 dark:hover:bg-stone-700 transition-colors disabled:opacity-50"
          >
            {isDownloadingWord ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
            Proposal
          </button>

          <button
            onClick={handleGenerateResearchPaper}
            disabled={isGeneratingPaper}
            className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg border border-stone-200 dark:border-stone-600 bg-white dark:bg-stone-800 text-stone-600 dark:text-stone-300 text-xs font-medium hover:bg-stone-50 dark:hover:bg-stone-700 transition-colors disabled:opacity-50"
          >
            {isGeneratingPaper ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileText className="h-3.5 w-3.5" />}
            Paper
          </button>
        </div>
      </div>
    </motion.div>
  );
};

export default ResultCard;